#!/usr/bin/env bash
set -e

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)

IMAGE="orga2"
TAG=$(find "$SCRIPT_DIR" -type f -exec sha256sum {} \; | sha256sum | cut -d' ' -f1)

if [[ -z $(docker images | grep $TAG) ]]; then
    docker build -t $IMAGE:$TAG $SCRIPT_DIR
fi

exec docker run --rm -ti -v $(pwd):/workspace -p 5900:5900 $IMAGE:$TAG bash
